services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ${DOCKERFILE}
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - /home/node/app/node_modules

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
