services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
